### ISSUE TITLE
Expr_Assign result should be var

### ISSUE THREAD

**Issue by quanyang** [ircmaxell/php-cfg#13]
In a typical program like this:
```
$a = $_GET['123'];
```

```
    Expr_ArrayDimFetch
        var: Var#1<$_GET>
        dim: LITERAL('123')
        result: Var#4
    Expr_Assign
        var: Var#5<$a>
        expr: Var#4
        result: Var#7
```

The Expr_Assign should have result: Var#5<$a> instead of Var#7.

**Comment by nikic** [comment]
I'm not sure it should. The `result` is the return value of the assignment itself, i.e. it's only relevant if you do something like `var_dump($a = $_GET['123'])`, otherwise `result` is ignored. The return value of the assignment is a temporary. Use of that temporary is not behaviorally identical to using the variable itself, in particular because it is always a value (while the variable itself may be a reference).

**Comment by quanyang** [comment]
Yes, you're right on that, I forgot about that use case.
